# Generated by Django 4.2 on 2023-05-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='manage',
            new_name='manager',
        ),
    ]
